services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on: [
      database
    ]
    links:
      - database
  database:
    image: "postgres:11-alpine3.18"
    ports:
      - '5432:5432'
    volumes:
      - database-storage:/var/lib/postgresql/data
#      Auto run the init database script. 
      - ./migrations/:/docker-entrypoint-initdb.d/
      - ./scripts/docker_startup/create_user_db.sh:/docker-entrypoint-initdb.d/create_user_db.sh
    env_file:
      - ./.env
volumes:
  database-storage:
    driver: local